import React, { createContext, useContext, useState, useEffect } from 'react';
import { syncGoogleTranslate, runDomTranslation, PHRASES } from '../lib/domTranslator';

export type LanguageCode = 'EN' | 'HI' | 'MR' | 'TA' | 'TE' | 'BN' | 'KN' | 'ML';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  native: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'EN', name: 'English', native: 'English' },
  { code: 'HI', name: 'Hindi', native: 'हिन्दी' },
  { code: 'MR', name: 'Marathi', native: 'मराठी' },
  { code: 'TA', name: 'Tamil', native: 'தமிழ்' },
  { code: 'TE', name: 'Telugu', native: 'తెలుగు' },
  { code: 'BN', name: 'Bengali', native: 'বাংলা' },
  { code: 'KN', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ML', name: 'Malayalam', native: 'മലയാളം' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  EN: {
    selectLanguage: 'SELECT LANGUAGE',
    shoppingInIndia: 'You are shopping on ShopNest India',
    all: 'All',
    todaysDeals: "Today's Deals",
    shopnestPay: 'ShopNest Pay',
    prime: 'Prime',
    electronics: 'Electronics',
    fashion: 'Fashion',
    homeKitchen: 'Home & Kitchen',
    homeLiving: 'Home & Living',
    beauty: 'Beauty',
    sports: 'Sports',
    computers: 'Computers',
    mobiles: 'Mobiles',
    minitv: 'miniTV',
    sell: 'Sell',
    customerService: 'Customer Service',
    searchPlaceholder: 'Search for products, brands and more...',
    deliverTo: 'Deliver to',
    helloSignIn: 'Hello, sign in',
    accountsLists: 'Account & Lists',
    returnsOrders: 'Returns & Orders',
    cart: 'Cart',
    wishlist: 'Wishlist',
    allCategories: 'All Categories',
    yourOrders: 'Your Orders',
    trackReturnSubtitle: 'Track, return, or buy items again in real time',
    ordersTab: 'Orders',
    buyAgain: 'Buy Again',
    notYetShipped: 'Not Yet Shipped',
    cancelledOrders: 'Cancelled Orders',
    rechargesBillPayments: 'Recharges & Bill Payments',
    payBillsSeamlessly: 'Pay bills seamlessly and earn instant scratch rewards',
    bharatBillPay: 'Bharat BillPay Enabled',
    mobilePrepaid: 'Mobile Prepaid',
    dthRecharge: 'DTH Recharge',
    electricityBill: 'Electricity Bill',
    gasCylinder: 'Gas Cylinder',
    fastagRecharge: 'FASTag Recharge',
    googlePlay: 'Google Play',
    becomeSeller: 'BECOME A SHOPNEST SELLER',
    sellOnAmazon: 'Sell on ShopNest — Reach Crores of Customers',
    sellSubtitle: "Launch your business on India's most visited shopping destination with 0% fee on select categories for the first 30 days.",
    startSellingToday: 'Start Selling Today',
    registerYourBusiness: 'Register your business',
    registerSubtitle: 'All you need is a phone number, bank account, and GSTIN.',
    businessName: 'Business / Company Name',
    emailAddress: 'Email address',
    gstinNumber: 'GSTIN Number',
    primaryCategory: 'Primary Category',
    continueToSellerCentral: 'Continue to Seller Central',
    shopnestPlusMember: 'ShopNest Plus Member',
    unlimitedFreeDelivery: 'Unlimited FREE Fast Delivery & Exclusive Member Discounts',
    joinShopNestPlus: 'Join ShopNest Plus. Enjoy zero delivery charges on all orders, early access to flash sales, extended 14-day returns, and special member-only prices.',
    startFreeTrial: 'Start your 30-day FREE Trial',
    annualPlan: 'Annual Plan',
    monthlyPlan: 'Monthly Plan',
    bestValueSave: 'Best value • Save ₹789 every year',
    flexibleBilling: 'Flexible monthly billing',
    watchTopSeries: 'Watch Top Web Series & Movies for Free',
    miniTVBannerDesc: 'No subscription required. Stream unlimited trending shows, comedies, and originals directly on ShopNest.',
    startWatching: 'Start Watching',
    trendingOnMiniTV: 'Trending on ShopNest miniTV',
    viewAll: 'View All',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    trackPackage: 'Track Package',
    viewItem: 'View item',
    invoice: 'Invoice',
    episodes: 'Episodes',
    orderPlaced: 'Order Placed',
    total: 'Total',
    shipTo: 'Ship To',
    orderId: 'Order ID',
    heroTagline: "India's #1 Smart Shopping Platform",
    heroHeadline: 'Upgrade Your Everyday Life',
    heroSubtitle: 'Discover top-quality products, unbeatable prices and a smoother shopping experience.',
    shopNow: 'Shop Now',
    tryPrime: 'Try Prime',
    freeDelivery: 'Free Delivery',
    freeDeliverySub: 'On orders above Rs.499',
    easyReturns: '10-Day Returns',
    easyReturnsSub: 'Hassle free',
    hugeSelection: '2.5 Cr+ Products',
    hugeSelectionSub: 'Huge selection',
    flashDealLive: 'Flash Deal Live!',
    upTo67Off: 'Up to 67% off',
    betterChoices: 'Better Choices, Brighter Days',
    trendingNow: 'Trending Now',
    recommendedForYou: 'Recommended for You',
    basedOnHistory: 'Based on your browsing history',
    moreToExplore: 'More to Explore',
    browseAll: 'Browse All',
    bestDeals: 'Best Deals',
    endsIn: 'Ends in',
    newDealsEveryHour: 'New deals every hour',
    viewAllDeals: 'View All Deals',
    homeEssentials: 'Home Essentials for a Better Tomorrow',
    homeEssentialsSub: 'Stylish. Functional. Made for You.',
    shopHome: 'Shop Home',
    primeBenefitsLink: 'Prime benefits',
    newArrivals: 'New Arrivals',
    catElectronics: 'Electronics',
    catFashion: 'Fashion',
    catHomeLiving: 'Home & Living',
    catBeauty: 'Beauty',
    catSports: 'Sports',
    catToysGames: 'Toys & Games',
    catMobiles: 'Mobiles',
    catBooks: 'Books',
    catAudio: 'Audio',
    catBaby: 'Baby',
    catKitchen: 'Kitchen',
    catCameras: 'Cameras',
    shoppingCart: 'Shopping Cart',
    cartEmpty: 'Your Cart is Empty',
    cartEmptyDesc: "Looks like you haven't added anything yet.",
    exploreProducts: 'Explore Products',
    itemDetails: 'Item Details',
    clearCart: 'Clear Cart',
    inStockFreeDelivery: 'In Stock - Eligible for Free Delivery',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    free: 'FREE',
    totalAmount: 'Total Amount',
    proceedToCheckout: 'Proceed to Checkout',
    secureCheckout: 'Safe & Secure 256-bit encrypted checkout',
    item: 'item',
    items: 'items',
    searchResults: 'Search Results',
    searchResultsFor: 'results for',
    noResultsFound: 'No Results Found',
    noResultsDesc: 'Try a different search term or browse our categories.',
    filters: 'Filters',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    topRatedSort: 'Top Rated',
    minRatingLabel: 'Min Rating',
    inStockOnlyLabel: 'In Stock Only',
    maxPriceLabel: 'Max Price',
    clearFilters: 'Clear Filters',
    productsFound: 'products found',
    myWishlist: 'My Wishlist',
    wishlistEmpty: 'Your Wishlist is Empty',
    wishlistEmptyDesc: 'Save items you love by tapping the heart icon on any product.',
    startShopping: 'Start Shopping',
    removeFromWishlist: 'Remove',
    noOrdersYet: 'No Orders Yet',
    noOrdersDesc: 'Your completed orders will appear here. Start shopping!',
    delivered: 'Delivered',
    processing: 'Processing',
    checkout: 'Checkout',
    placeOrder: 'Place Order',
    orderConfirmed: 'Order Confirmed!',
    continueShopping: 'Continue Shopping',
    helpCenter: 'Help Center',
    howCanWeHelp: 'How can we help you?',
    backToTop: 'Back to top',
    followUs: 'Follow Us',
    weAccept: 'We Accept',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: 'All rights reserved',
    quickAdd: 'Quick Add',
    added: 'Added!',
    topRatedBadge: 'Top Rated',
    bestSeller: 'Best Seller',
    onlyLeft: 'Only',
    leftInStock: 'left',
    freeDeliveryBadge: 'Free Delivery',
  },
  HI: {
    selectLanguage: 'भाषा चुनें',
    shoppingInIndia: 'आप शॉपनेस्ट इंडिया पर खरीदारी कर रहे हैं',
    all: 'सभी',
    todaysDeals: 'आज के डील्स',
    shopnestPay: 'शॉपनेस्ट पे',
    prime: 'प्राइम',
    electronics: 'इलेक्ट्रॉनिक्स',
    fashion: 'फैशन',
    homeKitchen: 'होम और किचन',
    homeLiving: 'होम और लिविंग',
    beauty: 'ब्यूटी',
    sports: 'स्पोर्ट्स',
    computers: 'कंप्यूटर्स',
    mobiles: 'मोबाइल',
    minitv: 'मिनी टीवी',
    sell: 'बेचें',
    customerService: 'ग्राहक सेवा',
    searchPlaceholder: 'उत्पाद, ब्रांड और बहुत कुछ खोजें...',
    deliverTo: 'डिलीवरी करें',
    helloSignIn: 'नमस्ते, साइन इन करें',
    accountsLists: 'खाता और सूचियां',
    returnsOrders: 'रिटर्न और ऑर्डर',
    cart: 'कार्ट',
    wishlist: 'विशलिस्ट',
    allCategories: 'सभी श्रेणियां',
    yourOrders: 'आपके ऑर्डर',
    trackReturnSubtitle: 'वास्तविक समय में ट्रैक करें, वापस करें या दोबारा खरीदें',
    ordersTab: 'ऑर्डर',
    buyAgain: 'दोबारा खरीदें',
    notYetShipped: 'अभी भेजा नहीं गया',
    cancelledOrders: 'रद्द किए गए ऑर्डर',
    rechargesBillPayments: 'रिचार्ज और बिल भुगतान',
    payBillsSeamlessly: 'निर्बाध रूप से बिलों का भुगतान करें और तत्काल स्क्रैच पुरस्कार पाएं',
    bharatBillPay: 'भारत बिलपे सक्षम',
    mobilePrepaid: 'मोबाइल प्रीपेड',
    dthRecharge: 'डीटीएच रिचार्ज',
    electricityBill: 'बिजली का बिल',
    gasCylinder: 'गैस सिलेंडर',
    fastagRecharge: 'फास्टैग रिचार्ज',
    googlePlay: 'गूगल प्ले',
    becomeSeller: 'ShopNest सेलर बनें',
    sellOnAmazon: 'ShopNest पर बेचें — करोड़ों ग्राहकों तक पहुंचें',
    sellSubtitle: 'पहले 30 दिनों के लिए चयनित श्रेणियों पर 0% शुल्क के साथ भारत के सबसे बड़े प्लेटफॉर्म पर व्यवसाय शुरू करें।',
    startSellingToday: 'आज ही बेचना शुरू करें',
    registerYourBusiness: 'अपना व्यवसाय पंजीकृत करें',
    registerSubtitle: 'आपको केवल एक फोन नंबर, बैंक खाता और जीएसटी नंबर चाहिए।',
    businessName: 'व्यवसाय / कंपनी का नाम',
    emailAddress: 'ईमेल पता',
    gstinNumber: 'जीएसटी नंबर',
    primaryCategory: 'प्राथमिक श्रेणी',
    continueToSellerCentral: 'सेलर सेंट्रल पर जारी रखें',
    shopnestPlusMember: 'शॉपनेस्ट प्लस सदस्य',
    unlimitedFreeDelivery: 'असीमित मुफ्त त्वरित डिलीवरी और विशेष छूट',
    joinShopNestPlus: 'शॉपनेस्ट प्लस से जुड़ें। शून्य डिलीवरी शुल्क, शुरुआती सेल एक्सेस और विशेष सदस्य मूल्यों का आनंद लें।',
    startFreeTrial: 'अपना 30-दिवसीय निःशुल्क परीक्षण शुरू करें',
    annualPlan: 'वार्षिक योजना',
    monthlyPlan: 'मासिक योजना',
    bestValueSave: 'सर्वोत्तम मूल्य • हर साल ₹789 बचाएं',
    flexibleBilling: 'लचीला मासिक बिलिंग',
    watchTopSeries: 'शीर्ष वेब श्रृंखला और फिल्में मुफ्त में देखें',
    miniTVBannerDesc: 'किसी सदस्यता की आवश्यकता नहीं। असीमित ट्रेंडिंग शो, कॉमेडी और मूल सामग्री मुफ्त देखें।',
    startWatching: 'देखना शुरू करें',
    trendingOnMiniTV: 'अमेज़न मिनी टीवी पर ट्रेंडिंग',
    viewAll: 'सभी देखें',
    addToCart: 'कार्ट में जोड़ें',
    buyNow: 'अभी खरीदें',
    trackPackage: 'पैकेज ट्रैक करें',
    viewItem: 'वस्तु देखें',
    invoice: 'चालान',
    episodes: 'एपिसोड',
    orderPlaced: 'ऑर्डर दिया गया',
    total: 'कुल',
    shipTo: 'पता',
    orderId: 'ऑर्डर आईडी',
  },
  MR: {
    selectLanguage: 'भाषा निवडा',
    shoppingInIndia: 'तुम्ही शॉपनेस्ट इंडियावर खरेदी करत आहात',
    all: 'सर्व',
    todaysDeals: 'आजचे डील्स',
    shopnestPay: 'शॉपनेस्ट पे',
    prime: 'प्राईम',
    electronics: 'इलेक्ट्रॉनिक्स',
    fashion: 'फॅशन',
    homeKitchen: 'होम आणि किचन',
    homeLiving: 'होम आणि लिव्हिंग',
    beauty: 'ब्युटी',
    sports: 'स्पोर्ट्स',
    computers: 'कॉम्प्युटर्स',
    mobiles: 'मोबाईल्स',
    minitv: 'मिनी टीव्ही',
    sell: 'विक्री करा',
    customerService: 'ग्राहक सेवा',
    searchPlaceholder: 'उत्पादने, ब्रँड आणि अधिक शोधा...',
    deliverTo: 'डिलिव्हर करा',
    helloSignIn: 'नमस्कार, साइन इन करा',
    accountsLists: 'खाते आणि यादी',
    returnsOrders: 'परतावा आणि ऑर्डर्स',
    cart: 'कार्ट',
    wishlist: 'विशलिस्ट',
    allCategories: 'सर्व श्रेणी',
    yourOrders: 'तुमच्या ऑर्डर्स',
    trackReturnSubtitle: 'रिअल टाइममध्ये ट्रॅक करा, परत करा किंवा पुन्हा खरेदी करा',
    ordersTab: 'ऑर्डर्स',
    buyAgain: 'पुन्हा खरेदी करा',
    notYetShipped: 'अद्याप पाठवले नाही',
    cancelledOrders: 'रद्द केलेल्या ऑर्डर्स',
    rechargesBillPayments: 'रिचार्ज आणि बिल पेमेंट्स',
    payBillsSeamlessly: 'सहजपणे बिले भरा आणि त्वरित स्क्रॅच बक्षिसे मिळवा',
    bharatBillPay: 'भारत बिलपे सक्षम',
    mobilePrepaid: 'मोबाईल प्रीपेड',
    dthRecharge: 'डीटीएच रिचार्ज',
    electricityBill: 'वीज बिल',
    gasCylinder: 'गॅस सिलिंडर',
    fastagRecharge: 'फास्टॅग रिचार्ज',
    googlePlay: 'गुगल प्ले',
    becomeSeller: 'अमेझॉन सेलर बना',
    sellOnAmazon: 'Amazon.in वर विका — करोडो ग्राहकांपर्यंत पोहोचा',
    sellSubtitle: 'पहिल्या ३० दिवसांसाठी निवडक श्रेणींवर ०% शुल्कासह भारताच्या सर्वात मोठ्या शॉपिंग प्लॅटफॉर्मवर व्यवसाय सुरू करा.',
    startSellingToday: 'आजच विक्री सुरू करा',
    registerYourBusiness: 'तुमच्या व्यवसायाची नोंदणी करा',
    registerSubtitle: 'फक्त फोन नंबर, बँक खाते आणि जीएसटी क्रमांक आवश्यक आहे.',
    businessName: 'व्यवसाय / कंपनीचे नाव',
    emailAddress: 'ईमेल पत्ता',
    gstinNumber: 'जीएसटी क्रमांक',
    primaryCategory: 'प्राथमिक श्रेणी',
    continueToSellerCentral: 'सेलर सेंट्रल वर जा',
    shopnestPlusMember: 'शॉपनेस्ट प्लस सदस्य',
    unlimitedFreeDelivery: 'अमर्यादित मोफत जलद डिलिव्हरी आणि विशेष सवलती',
    joinShopNestPlus: 'शॉपनेस्ट प्लसमध्ये सामील व्हा. सर्व ऑर्डर्सवर शून्य डिलिव्हरी शुल्क, फ्लॅश सेलमध्ये लवकर प्रवेश आणि विशेष सदस्य किमती मिळवा.',
    startFreeTrial: 'तुमची ३० दिवसांची मोफत चाचणी सुरू करा',
    annualPlan: 'वार्षिक योजना',
    monthlyPlan: 'मासिक योजना',
    bestValueSave: 'उत्तम मूल्य • दरवर्षी ₹७८९ वाचवा',
    flexibleBilling: 'लवचिक मासिक बिलिंग',
    watchTopSeries: 'टॉप वेब सीरिज आणि चित्रपट विनामूल्य पहा',
    miniTVBannerDesc: 'कोणत्याही सबस्क्रिप्शनची गरज नाही. ट्रेंडिंग शो, कॉमेडी आणि मूळ मालिका थेट मोफत पहा.',
    startWatching: 'पाहणे सुरू करा',
    trendingOnMiniTV: 'अमेझॉन मिनी टीव्ही वर ट्रेंडिंग',
    viewAll: 'सर्व पहा',
    addToCart: 'कार्टमध्ये जोडा',
    buyNow: 'आता खरेदी करा',
    trackPackage: 'पॅकेज ट्रॅक करा',
    viewItem: 'वस्तू पहा',
    invoice: 'इनव्हॉइस',
    episodes: 'भाग',
    orderPlaced: 'ऑर्डर तारीख',
    total: 'एकूण',
    shipTo: 'डिलिव्हरी पत्ता',
    orderId: 'ऑर्डर आयडी',
  },
  TA: {
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    shoppingInIndia: 'நீங்கள் ஷாப்நெஸ்ட் இந்தியாவில் ஷாப்பிங் செய்கிறீர்கள்',
    all: 'எல்லாம்',
    todaysDeals: 'இன்றைய சலுகைகள்',
    shopnestPay: 'ஷாப்நெஸ்ட் பே',
    prime: 'பிரைம்',
    electronics: 'எலக்ட்ரானிக்ஸ்',
    fashion: 'ஃபேஷன்',
    homeKitchen: 'வீடு மற்றும் சமையலறை',
    homeLiving: 'வீட்டு உபயோகம்',
    beauty: 'அழகு',
    sports: 'விளையாட்டு',
    computers: 'கணினிகள்',
    mobiles: 'மொபைல்கள்',
    minitv: 'மினி டிவி',
    sell: 'விற்க',
    customerService: 'வாடிக்கையாளர் சேவை',
    searchPlaceholder: 'தயாரிப்புகள், பிராண்டுகள் தேடுங்கள்...',
    deliverTo: 'டெலிவரி',
    helloSignIn: 'வணக்கம், உள்நுழைக',
    accountsLists: 'கணக்கு மற்றும் பட்டியல்கள்',
    returnsOrders: 'ரிட்டர்ன்ஸ் & ஆர்டர்கள்',
    cart: 'கார்ட்',
    wishlist: 'விருப்பப்பட்டியல்',
    allCategories: 'அனைத்து பிரிவுகளும்',
    yourOrders: 'உங்கள் ஆர்டர்கள்',
    trackReturnSubtitle: 'நிகழ்நேரத்தில் கண்காணிக்கவும், திரும்பப் பெறவும் அல்லது மீண்டும் வாங்கவும்',
    ordersTab: 'ஆர்டர்கள்',
    buyAgain: 'மீண்டும் வாங்கவும்',
    notYetShipped: 'இன்னும் அனுப்பப்படவில்லை',
    cancelledOrders: 'ரத்து செய்யப்பட்ட ஆர்டர்கள்',
    rechargesBillPayments: 'ரீசார்ஜ் மற்றும் பில் கட்டணங்கள்',
    payBillsSeamlessly: 'பில்களை செலுத்தி உடனடி வெகுமதிகளைப் பெறுங்கள்',
    bharatBillPay: 'பாரத் பில்பே இயக்கப்பட்டது',
    mobilePrepaid: 'மொபைல் ப்ரீபெய்ட்',
    dthRecharge: 'டிடிஹெச் ரீசார்ஜ்',
    electricityBill: 'மின் கட்டணம்',
    gasCylinder: 'எரிவாயு சிலிண்டர்',
    fastagRecharge: 'ஃபாஸ்டேக் ரீசார்ஜ்',
    googlePlay: 'கூகிள் பிளே',
    becomeSeller: 'அமேசான் விற்பனையாளராகுங்கள்',
    sellOnAmazon: 'Amazon.in இல் விற்கவும் — கோடிக்கணக்கான வாடிக்கையாளர்களை அடையுங்கள்',
    sellSubtitle: 'முதல் 30 நாட்களுக்கு 0% கட்டணத்தில் உங்கள் வணிகத்தைத் தொடங்குங்கள்.',
    startSellingToday: 'இன்றே விற்பனையைத் தொடங்குங்கள்',
    registerYourBusiness: 'உங்கள் வணிகத்தை பதிவு செய்யுங்கள்',
    registerSubtitle: 'தொலைபேசி எண், வங்கி கணக்கு மற்றும் ஜிஎஸ்டி எண் மட்டுமே தேவை.',
    businessName: 'வணிகம் / நிறுவனத்தின் பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    gstinNumber: 'ஜிஎஸ்டி எண்',
    primaryCategory: 'முதன்மை பிரிவு',
    continueToSellerCentral: 'விற்பனையாளர் மையத்திற்கு தொடரவும்',
    shopnestPlusMember: 'ஷாப்நெஸ்ட் பிளஸ் உறுப்பினர்',
    unlimitedFreeDelivery: 'வரம்பற்ற இலவச விரைவு டெலிவரி மற்றும் பிரத்யேக தள்ளுபடிகள்',
    joinShopNestPlus: 'ஷாப்நெஸ்ட் பிளஸில் சேருங்கள். பூஜ்ஜிய டெலிவரி கட்டணங்கள் மற்றும் பிரத்யேக விலைகளை அனுபவிக்கவும்.',
    startFreeTrial: 'உங்கள் 30 நாள் இலவச சோதனையைத் தொடங்குங்கள்',
    annualPlan: 'வருடாந்திர திட்டம்',
    monthlyPlan: 'மாதாந்திர திட்டம்',
    bestValueSave: 'சிறந்த மதிப்பு • ஆண்டுக்கு ₹789 சேமிக்கவும்',
    flexibleBilling: 'நெகிழ்வான மாதாந்திர கட்டணம்',
    watchTopSeries: 'சிறந்த வலைத் தொடர்கள் மற்றும் திரைப்படங்களை இலவசமாகப் பாருங்கள்',
    miniTVBannerDesc: 'சந்தா தேவையில்லை. சிறந்த நிகழ்ச்சிகளை அமேசானில் நேரடியாக இலவசமாகப் பார்க்கலாம்.',
    startWatching: 'பார்க்கத் தொடங்குங்கள்',
    trendingOnMiniTV: 'அமேசான் மினி டிவியில் டிரெண்டிங்',
    viewAll: 'அனைத்தையும் காட்டு',
    addToCart: 'கார்ட்டில் சேர்',
    buyNow: 'இப்போது வாங்கவும்',
    trackPackage: 'பேக்கேஜை கண்காணிக்கவும்',
    viewItem: 'பொருளைப் பார்',
    invoice: 'விலைப்பட்டியல்',
    episodes: 'எபிசோடுகள்',
    orderPlaced: 'ஆர்டர் தேதி',
    total: 'மொத்தம்',
    shipTo: 'முகவரி',
    orderId: 'ஆர்டர் எண்',
  },
  TE: {
    selectLanguage: 'భాషను ఎంచుకోండి',
    shoppingInIndia: 'మీరు షాప్‌నెస్ట్ ఇండియాలో షాపింగ్ చేస్తున్నారు',
    all: 'అన్ని',
    todaysDeals: 'నేటి డీల్స్',
    shopnestPay: 'షాప్‌నెస్ట్ పే',
    prime: 'ప్రైమ్',
    electronics: 'ఎలక్ట్రానిక్స్',
    fashion: 'ఫ్యాషన్',
    homeKitchen: 'హోమ్ & కిచెన్',
    homeLiving: 'గృహోపకరణాలు',
    beauty: 'బ్యూటీ',
    sports: 'క్రీడలు',
    computers: 'కంప్యూటర్లు',
    mobiles: 'మొబైల్స్',
    minitv: 'మినీ టీవీ',
    sell: 'అమ్మండి',
    customerService: 'కస్టమర్ సేవ',
    searchPlaceholder: 'ఉత్పత్తులు, బ్రాండ్‌ల కోసం శోధించండి...',
    deliverTo: 'డెలివరీ',
    helloSignIn: 'నమస్కారం, సైన్ ఇన్ చేయండి',
    accountsLists: 'ఖాతా & జాబితాలు',
    returnsOrders: 'రిటర్న్స్ & ఆర్డర్లు',
    cart: 'కార్ట్',
    wishlist: 'విష్‌లిస్ట్',
    allCategories: 'అన్ని వర్గాలు',
    yourOrders: 'మీ ఆర్డర్లు',
    trackReturnSubtitle: 'రియల్ టైమ్‌లో ట్రాక్ చేయండి, రిటర్న్ చేయండి లేదా మళ్లీ కొనండి',
    ordersTab: 'ఆర్డర్లు',
    buyAgain: 'మళ్లీ కొనండి',
    notYetShipped: 'ఇంకా రవాణా కాలేదు',
    cancelledOrders: 'రద్దు చేసిన ఆర్డర్లు',
    rechargesBillPayments: 'రీఛార్జ్‌లు & బిల్లు చెల్లింపులు',
    payBillsSeamlessly: 'బిల్లులను సులభంగా చెల్లించి తక్షణ స్క్రాచ్ రివార్డులను పొందండి',
    bharatBillPay: 'భారత్ బిల్‌పే ప్రారంభించబడింది',
    mobilePrepaid: 'మొబైల్ ప్రీపెయిడ్',
    dthRecharge: 'డిటిహెచ్ రీఛార్జ్',
    electricityBill: 'విద్యుత్ బిల్లు',
    gasCylinder: 'గ్యాస్ సిలిండర్',
    fastagRecharge: 'ఫాస్ట్‌ట్యాగ్ రీఛార్జ్',
    googlePlay: 'గూగుల్ ప్లే',
    becomeSeller: 'అమెజాన్ విక్రేత అవ్వండి',
    sellOnAmazon: 'Amazon.in లో అమ్మండి — కోట్ల మంది కస్టమర్లను చేరుకోండి',
    sellSubtitle: 'మొదటి 30 రోజులు 0% రుసుముతో భారతదేశపు అతిపెద్ద మార్కెట్‌లో మీ వ్యాపారాన్ని ప్రారంభించండి.',
    startSellingToday: 'ఈరోజే అమ్మడం ప్రారంభించండి',
    registerYourBusiness: 'మీ వ్యాపారాన్ని నమోదు చేయండి',
    registerSubtitle: 'ఫోన్ నంబర్, బ్యాంక్ ఖాతా మరియు జీఎస్టీ నంబర్ మాత్రమే అవసరం.',
    businessName: 'వ్యాపారం / కంపెనీ పేరు',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    gstinNumber: 'జీఎస్టీ నంబర్',
    primaryCategory: 'ప్రధాన వర్గం',
    continueToSellerCentral: 'సెల్లర్ సెంట్రల్‌కు కొనసాగండి',
    shopnestPlusMember: 'షాప్‌నెస్ట్ ప్లస్ సభ్యుడు',
    unlimitedFreeDelivery: 'అపరిమిత ఉచిత వేగవంతమైన డెలివరీ & ప్రత్యేక సభ్యుల తగ్గింపులు',
    joinShopNestPlus: 'షాప్‌నెస్ట్ ప్లస్‌లో చేరండి. ఉచిత డెలివరీ మరియు ప్రత్యేక ప్రయోజనాలను ఆస్వాదించండి.',
    startFreeTrial: 'మీ 30 రోజుల ఉచిత ట్రయల్ ప్రారంభించండి',
    annualPlan: 'వార్షిక ప్రణాళిక',
    monthlyPlan: 'నెలవారీ ప్రణాళిక',
    bestValueSave: 'ఉత్తమ విలువ • ప్రతి సంవత్సరం ₹789 ఆదా చేసుకోండి',
    flexibleBilling: 'సౌకర్యవంతమైన నెలవారీ బిల్లింగ్',
    watchTopSeries: 'అగ్ర వెబ్ సిరీస్ & సినిమాలను ఉచితంగా చూడండి',
    miniTVBannerDesc: 'సబ్‌స్క్రిప్షన్ అవసరం లేదు. ట్రెండింగ్ షోలు మరియు కామెడీలను అమెజాన్‌లో ఉచితంగా చూడండి.',
    startWatching: 'చూడటం ప్రారంభించండి',
    trendingOnMiniTV: 'అమెజాన్ మినీ టీవీలో ట్రెండింగ్',
    viewAll: 'అన్నీ చూడండి',
    addToCart: 'కార్ట్‌కు జోడించండి',
    buyNow: 'ఇప్పుడే కొనండి',
    trackPackage: 'ప్యాకేజీని ట్రాక్ చేయండి',
    viewItem: 'వస్తువును చూడండి',
    invoice: 'ఇన్వాయిస్',
    episodes: 'ఎపిసోడ్‌లు',
    orderPlaced: 'ఆర్డర్ తేదీ',
    total: 'మొత్తం',
    shipTo: 'చిరునామా',
    orderId: 'ఆర్డర్ ఐడి',
  },
  BN: {
    selectLanguage: 'ভাষা নির্বাচন করুন',
    shoppingInIndia: 'আপনি শপনেস্ট ইন্ডিয়ায় কেনাকাটা করছেন',
    all: 'সব',
    todaysDeals: 'আজকের ডিল',
    shopnestPay: 'শপনেস্ট পে',
    prime: 'প্রাইম',
    electronics: 'ইলেকট্রনিক্স',
    fashion: 'ফ্যাশন',
    homeKitchen: 'হোম ও কিচেন',
    homeLiving: 'হোম ও লিভিং',
    beauty: 'সৌন্দর্য',
    sports: 'খেলাধুলা',
    computers: 'কম্পিউটার',
    mobiles: 'মোবাইল',
    minitv: 'মিনি টিভি',
    sell: 'বিক্রি করুন',
    customerService: 'গ্রাহক সেবা',
    searchPlaceholder: 'পণ্য, ব্র্যান্ড এবং আরও অনেক কিছু খুঁজুন...',
    deliverTo: 'ডেলিভারি',
    helloSignIn: 'নমস্কার, সাইন ইন করুন',
    accountsLists: 'অ্যাকাউন্ট ও তালিকা',
    returnsOrders: 'রিটার্ন ও অর্ডার',
    cart: 'কার্ট',
    wishlist: 'উইশলিস্ট',
    allCategories: 'সমস্ত বিভাগ',
    yourOrders: 'আপনার অর্ডার',
    trackReturnSubtitle: 'রিয়েল টাইমে ট্র্যাক করুন, ফেরত দিন বা আবার কিনুন',
    ordersTab: 'অর্ডার',
    buyAgain: 'আবার কিনুন',
    notYetShipped: 'এখনও পাঠানো হয়নি',
    cancelledOrders: 'বাতিল অর্ডার',
    rechargesBillPayments: 'রিচার্জ ও বিল পেমেন্ট',
    payBillsSeamlessly: 'নির্বিঘ্নে বিল পরিশোধ করুন এবং তাত্ক্ষণিক স্ক্র্যাচ পুরস্কার জিতুন',
    bharatBillPay: 'ভারত বিলপে সক্ষম',
    mobilePrepaid: 'মোবাইল প্রিপেইড',
    dthRecharge: 'ডিটিএইচ রিচার্জ',
    electricityBill: 'বিদ্যুৎ বিল',
    gasCylinder: 'গ্যাস সিলিন্ডার',
    fastagRecharge: 'ফাস্ট্যাগ রিচার্জ',
    googlePlay: 'গুগল প্লে',
    becomeSeller: 'অ্যামাজন সেলার হন',
    sellOnAmazon: 'Amazon.in এ বিক্রি করুন — কোটি কোটি গ্রাহকের কাছে পৌঁছান',
    sellSubtitle: 'প্রথম ৩০ দিনের জন্য ০% ফিতে আপনার ব্যবসা শুরু করুন।',
    startSellingToday: 'আজই বিক্রি শুরু করুন',
    registerYourBusiness: 'আপনার ব্যবসা নিবন্ধন করুন',
    registerSubtitle: 'শুধু ফোন নম্বর, ব্যাঙ্ক অ্যাকাউন্ট এবং জিএসটি নম্বর প্রয়োজন।',
    businessName: 'ব্যবসা / কোম্পানির নাম',
    emailAddress: 'ইমেইল ঠিকানা',
    gstinNumber: 'জিএসটি নম্বর',
    primaryCategory: 'প্রাথমিক বিভাগ',
    continueToSellerCentral: 'বিক্রেতা সেন্টারে এগিয়ে যান',
    shopnestPlusMember: 'শপনেস্ট প্লাস সদস্য',
    unlimitedFreeDelivery: 'সীমাহীন বিনামূল্যে দ্রুত ডেলিভারি ও বিশেষ ছাড়',
    joinShopNestPlus: 'শপনেস্ট প্লাসে যোগ দিন। বিনামূল্যে ডেলিভারি এবং বিশেষ সদস্য সুবিধা উপভোগ করুন।',
    startFreeTrial: 'আপনার ৩০ দিনের বিনামূল্যে ট্রায়াল শুরু করুন',
    annualPlan: 'বার্ষিক পরিকল্পনা',
    monthlyPlan: 'মাসিক পরিকল্পনা',
    bestValueSave: 'সেরা মূল্য • প্রতি বছর ₹৭৮৯ সাশ্রয় করুন',
    flexibleBilling: 'নমনীয় মাসিক বিলিং',
    watchTopSeries: 'সেরা ওয়েব সিরিজ এবং সিনেমা বিনামূল্যে দেখুন',
    miniTVBannerDesc: 'কোন সাবস্ক্রিপশন প্রয়োজন নেই। ট্রেন্ডিং শোগুলি সরাসরি বিনামূল্যে উপভোগ করুন।',
    startWatching: 'দেখা শুরু করুন',
    trendingOnMiniTV: 'অ্যামাজন মিনি টিভিতে ট্রেন্ডিং',
    viewAll: 'সবগুলো দেখুন',
    addToCart: 'কার্টে যোগ করুন',
    buyNow: 'এখনই কিনুন',
    trackPackage: 'প্যাকেজ ট্র্যাক করুন',
    viewItem: 'আইটেম দেখুন',
    invoice: 'চালান',
    episodes: 'পর্ব',
    orderPlaced: 'অর্ডারের তারিখ',
    total: 'মোট',
    shipTo: 'ঠিকানা',
    orderId: 'অর্ডার আইডি',
  },
  KN: {
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    shoppingInIndia: 'ನೀವು ಶಾಪ್‌ನೆಸ್ಟ್ ಇಂಡಿಯಾದಲ್ಲಿ ಶಾಪಿಂಗ್ ಮಾಡುತ್ತಿದ್ದೀರಿ',
    all: 'ಎಲ್ಲಾ',
    todaysDeals: 'ಇಂದಿನ ಡೀಲ್ಸ್',
    shopnestPay: 'ಶಾಪ್‌ನೆಸ್ಟ್ ಪೇ',
    prime: 'ಪ್ರೈಮ್',
    electronics: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್',
    fashion: 'ಫ್ಯಾಷನ್',
    homeKitchen: 'ಮನೆ ಮತ್ತು ಅಡುಗೆಮನೆ',
    homeLiving: 'ಗೃಹೋಪಯೋಗಿ',
    beauty: 'ಸೌಂದರ್ಯ',
    sports: 'ಕ್ರೀಡೆಗಳು',
    computers: 'ಕಂಪ್ಯೂಟರ್‌ಗಳು',
    mobiles: 'ಮೊಬೈಲ್‌ಗಳು',
    minitv: 'ಮಿನಿ ಟಿವಿ',
    sell: 'ಮಾರಾಟ ಮಾಡಿ',
    customerService: 'ಗ್ರಾಹಕ ಸೇವೆ',
    searchPlaceholder: 'ಉತ್ಪನ್ನಗಳು, ಬ್ರ್ಯಾಂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    deliverTo: 'ತಲುಪಿಸಿ',
    helloSignIn: 'ನಮಸ್ಕಾರ, ಸೈನ್ ಇನ್ ಮಾಡಿ',
    accountsLists: 'ಖಾತೆ ಮತ್ತು ಪಟ್ಟಿಗಳು',
    returnsOrders: 'ರಿಟರ್ನ್ಸ್ ಮತ್ತು ಆದೇಶಗಳು',
    cart: 'ಕಾರ್ಟ್',
    wishlist: 'ಇಷ್ಟಪಟ್ಟಿ',
    allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    yourOrders: 'ನಿಮ್ಮ ಆದೇಶಗಳು',
    trackReturnSubtitle: 'ನೈಜ ಸಮಯದಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಹಿಂತಿರುಗಿಸಿ ಅಥವಾ ಮತ್ತೆ ಖರೀದಿಸಿ',
    ordersTab: 'ಆದೇಶಗಳು',
    buyAgain: 'ಮತ್ತೆ ಖರೀದಿಸಿ',
    notYetShipped: 'ಇನ್ನೂ ಕಳುಹಿಸಲಾಗಿಲ್ಲ',
    cancelledOrders: 'ರದ್ದುಗೊಳಿಸಲಾದ ಆದೇಶಗಳು',
    rechargesBillPayments: 'ರೀಚಾರ್ಜ್ ಮತ್ತು ಬಿಲ್ ಪಾವತಿಗಳು',
    payBillsSeamlessly: 'ಬಿಲ್‌ಗಳನ್ನು ಸುಲಭವಾಗಿ ಪಾವತಿಸಿ ಮತ್ತು ತತ್‌ಕ್ಷಣ ಸ್ಕ್ರ್ಯಾಚ್ ಬಹುಮಾನಗಳನ್ನು ಗಳಿಸಿ',
    bharatBillPay: 'ಭಾರತ್ ಬಿಲ್‌ಪೇ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ',
    mobilePrepaid: 'ಮೊಬೈಲ್ ಪ್ರಿಪೇಯ್ಡ್',
    dthRecharge: 'ಡಿಟಿಎಚ್ ರೀಚಾರ್ಜ್',
    electricityBill: 'ವಿದ್ಯುತ್ ಬಿಲ್',
    gasCylinder: 'ಗ್ಯಾಸ್ ಸಿಲಿಂಡರ್',
    fastagRecharge: 'ಫಾಸ್ಟ್ಯಾಗ್ ರೀಚಾರ್ಜ್',
    googlePlay: 'ಗೂಗಲ್ ಪ್ಲೇ',
    becomeSeller: 'ಅಮೆಜಾನ್ ಮಾರಾಟಗಾರರಾಗಿ',
    sellOnAmazon: 'Amazon.in ನಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ — ಕೋಟ್ಯಂತರ ಗ್ರಾಹಕರನ್ನು ತಲುಪಿ',
    sellSubtitle: 'ಮೊದಲ 30 ದಿನಗಳವರೆಗೆ 0% ಶುಲ್ಕದೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಾರಂಭಿಸಿ.',
    startSellingToday: 'ಇಂದೇ ಮಾರಾಟ ಪ್ರಾರಂಭಿಸಿ',
    registerYourBusiness: 'ನಿಮ್ಮ ವ್ಯವಹಾರವನ್ನು ನೋಂದಾಯಿಸಿ',
    registerSubtitle: 'ಫೋನ್ ಸಂಖ್ಯೆ, ಬ್ಯಾಂಕ್ ಖಾತೆ ಮತ್ತು ಜಿಎಸ್‌ಟಿ ಸಂಖ್ಯೆ ಮಾತ್ರ ಸಾಕು.',
    businessName: 'ವ್ಯಾಪಾರ / ಕಂಪನಿ ಹೆಸರು',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    gstinNumber: 'ಜಿಎಸ್‌ಟಿ ಸಂಖ್ಯೆ',
    primaryCategory: 'ಪ್ರಾಥಮಿಕ ವರ್ಗ',
    continueToSellerCentral: 'ಮಾರಾಟಗಾರರ ಕೇಂದ್ರಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ',
    shopnestPlusMember: 'ಶಾಪ್‌ನೆಸ್ಟ್ ಪ್ಲಸ್ ಸದಸ್ಯ',
    unlimitedFreeDelivery: 'ಅನಿಯಮಿತ ಉಚಿತ ವೇಗದ ವಿತರಣೆ ಮತ್ತು ವಿಶೇಷ ರಿಯಾಯಿತಿಗಳು',
    joinShopNestPlus: 'ಶಾಪ್‌ನೆಸ್ಟ್ ಪ್ಲಸ್‌ಗೆ ಸೇರಿ. ಉಚಿತ ವಿತರಣೆ ಮತ್ತು ವಿಶೇಷ ಸದಸ್ಯ ಪ್ರಯೋಜನಗಳನ್ನು ಆನಂದಿಸಿ.',
    startFreeTrial: 'ನಿಮ್ಮ 30 ದಿನಗಳ ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    annualPlan: 'ವಾರ್ಷಿಕ ಯೋಜನೆ',
    monthlyPlan: 'ಮಾಸಿಕ ಯೋಜನೆ',
    bestValueSave: 'ಉತ್ತಮ ಮೌಲ್ಯ • ಪ್ರತಿ ವರ್ಷ ₹789 ಉಳಿಸಿ',
    flexibleBilling: 'ಹೊಂದಿಕೊಳ್ಳುವ ಮಾಸಿಕ ಬಿಲ್ಲಿಂಗ್',
    watchTopSeries: 'ಉನ್ನತ ವೆಬ್ ಸರಣಿಗಳು ಮತ್ತು ಚಲನಚಿತ್ರಗಳನ್ನು ಉಚಿತವಾಗಿ ವೀಕ್ಷಿಸಿ',
    miniTVBannerDesc: 'ಯಾವುದೇ ಚಂದಾದಾರಿಕೆ ಅಗತ್ಯವಿಲ್ಲ. ಉನ್ನತ ಸರಣಿಗಳನ್ನು ನೇರವಾಗಿ ಉಚಿತವಾಗಿ ಆನಂದಿಸಿ.',
    startWatching: 'ವೀಕ್ಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
    trendingOnMiniTV: 'ಅಮೆಜಾನ್ ಮಿನಿ ಟಿವಿಯಲ್ಲಿ ಟ್ರೆಂಡಿಂಗ್',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    buyNow: 'ಈಗಲೇ ಖರೀದಿಸಿ',
    trackPackage: 'ಪ್ಯಾಕೇಜ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    viewItem: 'ಐಟಂ ವೀಕ್ಷಿಸಿ',
    invoice: 'ಸರಕುಪಟ್ಟಿ',
    episodes: 'ಕಂತುಗಳು',
    orderPlaced: 'ಆದೇಶದ ದಿನಾಂಕ',
    total: 'ಒಟ್ಟು',
    shipTo: 'ವಿಳಾಸ',
    orderId: 'ಆದೇಶ ಐಡಿ',
  },
  ML: {
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    shoppingInIndia: 'നിങ്ങൾ ഷോപ്പ്നെസ്റ്റ് ഇന്ത്യയിൽ ഷോപ്പിംഗ് നടത്തുന്നു',
    all: 'എല്ലാം',
    todaysDeals: 'ഇന്നത്തെ ഓഫറുകൾ',
    shopnestPay: 'ഷോപ്പ്നെസ്റ്റ് പേ',
    prime: 'പ്രൈം',
    electronics: 'ഇലക്ട്രോണിക്സ്',
    fashion: 'ഫാഷൻ',
    homeKitchen: 'വീടും അടുക്കളയും',
    homeLiving: 'ഹോം & ലിവിംഗ്',
    beauty: 'സൗന്ദര്യം',
    sports: 'കായിക ഇനങ്ങൾ',
    computers: 'കമ്പ്യൂട്ടറുകൾ',
    mobiles: 'മൊബൈലുകൾ',
    minitv: 'മിനി ടിവി',
    sell: 'വിൽക്കുക',
    customerService: 'ഉപഭോക്തൃ സേവനം',
    searchPlaceholder: 'ഉൽപ്പന്നങ്ങളും ബ്രാൻഡുകളും തിരയുക...',
    deliverTo: 'ഡെലിവറി',
    helloSignIn: 'നമസ്കാരം, സൈൻ ഇൻ ചെയ്യുക',
    accountsLists: 'അക്കൗണ്ടും ലിസ്റ്റുകളും',
    returnsOrders: 'റിട്ടേൺസും ഓർഡറുകളും',
    cart: 'കാർട്ട്',
    wishlist: 'വിഷ് ലിസ്റ്റ്',
    allCategories: 'എല്ലാ വിഭാഗങ്ങളും',
    yourOrders: 'നിങ്ങളുടെ ഓർഡറുകൾ',
    trackReturnSubtitle: 'തത്സമയം ട്രാക്ക് ചെയ്യുക, റിട്ടേൺ ചെയ്യുക അല്ലെങ്കിൽ വീണ്ടും വാങ്ങുക',
    ordersTab: 'ഓർഡറുകൾ',
    buyAgain: 'വീണ്ടും വാങ്ങുക',
    notYetShipped: 'ഇതുവരെ അയച്ചിട്ടില്ല',
    cancelledOrders: 'റദ്ദാക്കിയ ഓർഡറുകൾ',
    rechargesBillPayments: 'റീചാർജുകളും ബിൽ പേയ്‌മെന്റുകളും',
    payBillsSeamlessly: 'ബില്ലുകൾ തടസ്സമില്ലാതെ അടച്ച് തൽക്ഷണ സ്ക്രാച്ച് റിവാർഡുകൾ നേടുക',
    bharatBillPay: 'ഭാരത് ബിൽപേ സജ്ജമാക്കിയിരിക്കുന്നു',
    mobilePrepaid: 'മൊബൈൽ പ്രീപെയ്ഡ്',
    dthRecharge: 'ഡിടിഎച്ച് റീചാർജ്',
    electricityBill: 'വൈദ്യുതി ബിൽ',
    gasCylinder: 'ഗ്യാസ് സിലിണ്ടർ',
    fastagRecharge: 'ഫാസ്ടാഗ് റീചാർജ്',
    googlePlay: 'ഗൂഗിൾ പ്ലേ',
    becomeSeller: 'ആമസോൺ വിൽപ്പനക്കാരനാകൂ',
    sellOnAmazon: 'Amazon.in ൽ വിൽക്കൂ — കോടിക്കണക്കിന് ഉപഭോക്താക്കളിലേക്ക് എത്തൂ',
    sellSubtitle: 'ആദ്യ 30 ദിവസത്തേക്ക് 0% ഫീസിൽ നിങ്ങളുടെ ബിസിനസ്സ് ആരംഭിക്കൂ.',
    startSellingToday: 'ഇന്ന് തന്നെ വിൽക്കാൻ തുടങ്ങൂ',
    registerYourBusiness: 'നിങ്ങളുടെ ബിസിനസ്സ് രജിസ്റ്റർ ചെയ്യുക',
    registerSubtitle: 'ഫോൺ നമ്പർ, ബാങ്ക് അക്കൗണ്ട്, ജിഎസ്ടി നമ്പർ മാത്രം മതി.',
    businessName: 'ബിസിനസ്സ് / കമ്പനിയുടെ പേര്',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    gstinNumber: 'ജിഎസ്ടി നമ്പർ',
    primaryCategory: 'പ്രധാന വിഭാഗം',
    continueToSellerCentral: 'സെല്ലർ സെന്ററിലേക്ക് തുടരുക',
    shopnestPlusMember: 'ഷോപ്പ്നെസ്റ്റ് പ്ലസ് അംഗം',
    unlimitedFreeDelivery: 'അൺലിമിറ്റഡ് സൗജന്യ ഫാസ്റ്റ് ഡെലിവറിയും പ്രത്യേക കിഴിവുകളും',
    joinShopNestPlus: 'ഷോപ്പ്നെസ്റ്റ് പ്ലസിൽ ചേരുക. സൗജന്യ ഡെലിവറിയും പ്രത്യേക ഓഫറുകളും ആസ്വദിക്കൂ.',
    startFreeTrial: 'നിങ്ങളുടെ 30 ദിവസത്തെ സൗജന്യ ട്രയൽ ആരംഭിക്കുക',
    annualPlan: 'വാർഷിക പ്ലാൻ',
    monthlyPlan: 'പ്രതിമാസ പ്ലാൻ',
    bestValueSave: 'മികച്ച മൂല്യം • വർഷം തോറും ₹789 ലാഭിക്കൂ',
    flexibleBilling: 'സൗകര്യപ്രദമായ പ്രതിമാസ ബില്ലിംഗ്',
    watchTopSeries: 'മുൻനിര വെബ് സീരീസുകളും സിനിമകളും സൗജന്യമായി കാണുക',
    miniTVBannerDesc: 'സബ്‌സ്‌ക്രിപ്ഷൻ ആവശ്യമില്ല. ട്രെൻഡിംഗ് ഷോകൾ സൗജന്യമായി നേരിട്ട് ആസ്വദിക്കൂ.',
    startWatching: 'കാണാൻ തുടങ്ങൂ',
    trendingOnMiniTV: 'ആമസോൺ മിനി ടിവിയിൽ ട്രെൻഡിംഗ്',
    viewAll: 'എല്ലാം കാണുക',
    addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    buyNow: 'ഇപ്പോൾ വാങ്ങുക',
    trackPackage: 'പാക്കേജ് ട്രാക്ക് ചെയ്യുക',
    viewItem: 'ഇനം കാണുക',
    invoice: 'ഇൻവോയ്സ്',
    episodes: 'എപ്പിസോഡുകൾ',
    orderPlaced: 'ഓർഡർ തീയതി',
    total: 'ആകെ',
    shipTo: 'വിലാസം',
    orderId: 'ഓർഡർ ഐഡി',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'EN',
  setLanguage: () => {},
  t: (key, defaultText) => defaultText || key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('shopnest_lang') as LanguageCode;
    return saved && TRANSLATIONS[saved] ? saved : 'EN';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('shopnest_lang', lang);
    syncGoogleTranslate(lang);
    runDomTranslation(lang);
  };

  const t = (key: string, defaultText?: string): string => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.EN;
    if (currentDict && currentDict[key]) return currentDict[key];
    if (TRANSLATIONS.EN && TRANSLATIONS.EN[key]) return TRANSLATIONS.EN[key];
    if (defaultText) {
      const phraseDict = PHRASES[language];
      if (phraseDict && phraseDict[defaultText]) return phraseDict[defaultText];
      return defaultText;
    }
    return key;
  };

  useEffect(() => {
    // 1. Synchronize Google Translate with saved or active language
    syncGoogleTranslate(language);

    // 2. Initial instant DOM translation
    runDomTranslation(language);

    // 3. Keep translating dynamically loaded content & routes
    let debounceTimer: any = null;
    const observer = new MutationObserver(() => {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        runDomTranslation(language);
      }, 50);
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: false,
    });

    return () => {
      clearTimeout(debounceTimer);
      observer.disconnect();
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

